/**
 * @file src/local_coordinate_coding.cpp
 *
 * This is an autogenerated file containing implementations of C++ functions to
 * be called by the R local_coordinate_coding binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/local_coordinate_coding/local_coordinate_coding_main.cpp>

#define Realloc(p,n,t) (t *) R_chk_realloc( (void *)(p), (R_SIZE_T)((n) * sizeof(t)) )
#define Free(p)        (R_chk_free( (void *)(p) ), (p) = NULL)

// [[Rcpp::export]]
void local_coordinate_coding_call(SEXP params, SEXP timers)
{
  util::Params& p = *Rcpp::as<Rcpp::XPtr<util::Params>>(params);
  util::Timers& t = *Rcpp::as<Rcpp::XPtr<util::Timers>>(timers);

  if (p.Has("verbose"))
    Log::Info.ignoreInput = false;
  else
    Log::Info.ignoreInput = true;

  BINDING_FUNCTION(p, t);
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.

// Get the pointer to a LocalCoordinateCoding<> parameter.
// [[Rcpp::export]]
SEXP GetParamLocalCoordinateCodingPtr(SEXP params,
                                   const std::string& paramName,
                                   SEXP inputModels)
{
  util::Params& p = *Rcpp::as<Rcpp::XPtr<util::Params>>(params);
  Rcpp::List inputModelsList(inputModels);
  LocalCoordinateCoding<>* modelPtr = p.Get<LocalCoordinateCoding<>*>(paramName);
  for (int i = 0; i < inputModelsList.length(); ++i)
  {
    Rcpp::XPtr<LocalCoordinateCoding<>> inputModel =
        Rcpp::as<Rcpp::XPtr<LocalCoordinateCoding<>>>(inputModelsList[i]);
    // Don't create a new XPtr---just reuse the one given as input, so that we
    // don't end up deleting it twice.
    if (inputModel.get() == modelPtr)
      return inputModel;
  }

  return std::move((Rcpp::XPtr<LocalCoordinateCoding<>>) p.Get<LocalCoordinateCoding<>*>(paramName));
}

// Set the pointer to a LocalCoordinateCoding<> parameter.
// [[Rcpp::export]]
void SetParamLocalCoordinateCodingPtr(SEXP params, const std::string& paramName, SEXP ptr)
{
  util::Params& p = *Rcpp::as<Rcpp::XPtr<util::Params>>(params);
  p.Get<LocalCoordinateCoding<>*>(paramName) = Rcpp::as<Rcpp::XPtr<LocalCoordinateCoding<>>>(ptr);
  p.SetPassed(paramName);
}

// Serialize a LocalCoordinateCoding<> pointer.
// [[Rcpp::export]]
Rcpp::RawVector SerializeLocalCoordinateCodingPtr(SEXP ptr)
{
  std::ostringstream oss;
  {
    cereal::BinaryOutputArchive oa(oss);
    oa(cereal::make_nvp("LocalCoordinateCoding",
          *Rcpp::as<Rcpp::XPtr<LocalCoordinateCoding<>>>(ptr)));
  }

  Rcpp::RawVector raw_vec(oss.str().size());

  // Copy the string buffer so we can return one that won't get deallocated when
  // we exit this function.
  memcpy(&raw_vec[0], oss.str().c_str(), oss.str().size());
  raw_vec.attr("type") = "LocalCoordinateCoding";
  return raw_vec;
}

// Deserialize a LocalCoordinateCoding<> pointer.
// [[Rcpp::export]]
SEXP DeserializeLocalCoordinateCodingPtr(Rcpp::RawVector str)
{
  LocalCoordinateCoding<>* ptr = new LocalCoordinateCoding<>();

  std::istringstream iss(std::string((char *) &str[0], str.size()));
  {
    cereal::BinaryInputArchive ia(iss);
    ia(cereal::make_nvp("LocalCoordinateCoding", *ptr));
  }

  // R will be responsible for freeing this.
  return std::move((Rcpp::XPtr<LocalCoordinateCoding<>>)ptr);
}


