# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaboost_call <- function(params, timers) {
    invisible(.Call('_mlpack_adaboost_call', PACKAGE = 'mlpack', params, timers))
}

GetParamAdaBoostModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamAdaBoostModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamAdaBoostModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamAdaBoostModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeAdaBoostModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeAdaBoostModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeAdaBoostModelPtr <- function(str) {
    .Call('_mlpack_DeserializeAdaBoostModelPtr', PACKAGE = 'mlpack', str)
}

adaboost_classify_call <- function(params, timers) {
    invisible(.Call('_mlpack_adaboost_classify_call', PACKAGE = 'mlpack', params, timers))
}

adaboost_probabilities_call <- function(params, timers) {
    invisible(.Call('_mlpack_adaboost_probabilities_call', PACKAGE = 'mlpack', params, timers))
}

adaboost_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_adaboost_train_call', PACKAGE = 'mlpack', params, timers))
}

approx_kfn_call <- function(params, timers) {
    invisible(.Call('_mlpack_approx_kfn_call', PACKAGE = 'mlpack', params, timers))
}

GetParamApproxKFNModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamApproxKFNModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamApproxKFNModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamApproxKFNModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeApproxKFNModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeApproxKFNModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeApproxKFNModelPtr <- function(str) {
    .Call('_mlpack_DeserializeApproxKFNModelPtr', PACKAGE = 'mlpack', str)
}

bayesian_linear_regression_call <- function(params, timers) {
    invisible(.Call('_mlpack_bayesian_linear_regression_call', PACKAGE = 'mlpack', params, timers))
}

GetParamBayesianLinearRegressionPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamBayesianLinearRegressionPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamBayesianLinearRegressionPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamBayesianLinearRegressionPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeBayesianLinearRegressionPtr <- function(ptr) {
    .Call('_mlpack_SerializeBayesianLinearRegressionPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeBayesianLinearRegressionPtr <- function(str) {
    .Call('_mlpack_DeserializeBayesianLinearRegressionPtr', PACKAGE = 'mlpack', str)
}

bayesian_linear_regression_predict_call <- function(params, timers) {
    invisible(.Call('_mlpack_bayesian_linear_regression_predict_call', PACKAGE = 'mlpack', params, timers))
}

bayesian_linear_regression_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_bayesian_linear_regression_train_call', PACKAGE = 'mlpack', params, timers))
}

cf_call <- function(params, timers) {
    invisible(.Call('_mlpack_cf_call', PACKAGE = 'mlpack', params, timers))
}

GetParamCFModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamCFModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamCFModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamCFModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeCFModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeCFModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeCFModelPtr <- function(str) {
    .Call('_mlpack_DeserializeCFModelPtr', PACKAGE = 'mlpack', str)
}

dbscan_call <- function(params, timers) {
    invisible(.Call('_mlpack_dbscan_call', PACKAGE = 'mlpack', params, timers))
}

decision_tree_call <- function(params, timers) {
    invisible(.Call('_mlpack_decision_tree_call', PACKAGE = 'mlpack', params, timers))
}

GetParamDecisionTreeModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamDecisionTreeModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamDecisionTreeModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamDecisionTreeModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeDecisionTreeModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeDecisionTreeModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeDecisionTreeModelPtr <- function(str) {
    .Call('_mlpack_DeserializeDecisionTreeModelPtr', PACKAGE = 'mlpack', str)
}

decision_tree_classify_call <- function(params, timers) {
    invisible(.Call('_mlpack_decision_tree_classify_call', PACKAGE = 'mlpack', params, timers))
}

decision_tree_probabilities_call <- function(params, timers) {
    invisible(.Call('_mlpack_decision_tree_probabilities_call', PACKAGE = 'mlpack', params, timers))
}

decision_tree_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_decision_tree_train_call', PACKAGE = 'mlpack', params, timers))
}

det_call <- function(params, timers) {
    invisible(.Call('_mlpack_det_call', PACKAGE = 'mlpack', params, timers))
}

GetParamDTreePtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamDTreePtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamDTreePtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamDTreePtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeDTreePtr <- function(ptr) {
    .Call('_mlpack_SerializeDTreePtr', PACKAGE = 'mlpack', ptr)
}

DeserializeDTreePtr <- function(str) {
    .Call('_mlpack_DeserializeDTreePtr', PACKAGE = 'mlpack', str)
}

emst_call <- function(params, timers) {
    invisible(.Call('_mlpack_emst_call', PACKAGE = 'mlpack', params, timers))
}

fastmks_call <- function(params, timers) {
    invisible(.Call('_mlpack_fastmks_call', PACKAGE = 'mlpack', params, timers))
}

GetParamFastMKSModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamFastMKSModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamFastMKSModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamFastMKSModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeFastMKSModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeFastMKSModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeFastMKSModelPtr <- function(str) {
    .Call('_mlpack_DeserializeFastMKSModelPtr', PACKAGE = 'mlpack', str)
}

gmm_generate_call <- function(params, timers) {
    invisible(.Call('_mlpack_gmm_generate_call', PACKAGE = 'mlpack', params, timers))
}

gmm_probability_call <- function(params, timers) {
    invisible(.Call('_mlpack_gmm_probability_call', PACKAGE = 'mlpack', params, timers))
}

gmm_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_gmm_train_call', PACKAGE = 'mlpack', params, timers))
}

GetParamGMMPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamGMMPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamGMMPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamGMMPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeGMMPtr <- function(ptr) {
    .Call('_mlpack_SerializeGMMPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeGMMPtr <- function(str) {
    .Call('_mlpack_DeserializeGMMPtr', PACKAGE = 'mlpack', str)
}

hmm_generate_call <- function(params, timers) {
    invisible(.Call('_mlpack_hmm_generate_call', PACKAGE = 'mlpack', params, timers))
}

hmm_loglik_call <- function(params, timers) {
    invisible(.Call('_mlpack_hmm_loglik_call', PACKAGE = 'mlpack', params, timers))
}

hmm_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_hmm_train_call', PACKAGE = 'mlpack', params, timers))
}

GetParamHMMModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamHMMModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamHMMModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamHMMModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeHMMModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeHMMModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeHMMModelPtr <- function(str) {
    .Call('_mlpack_DeserializeHMMModelPtr', PACKAGE = 'mlpack', str)
}

hmm_viterbi_call <- function(params, timers) {
    invisible(.Call('_mlpack_hmm_viterbi_call', PACKAGE = 'mlpack', params, timers))
}

hoeffding_tree_call <- function(params, timers) {
    invisible(.Call('_mlpack_hoeffding_tree_call', PACKAGE = 'mlpack', params, timers))
}

GetParamHoeffdingTreeModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamHoeffdingTreeModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamHoeffdingTreeModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamHoeffdingTreeModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeHoeffdingTreeModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeHoeffdingTreeModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeHoeffdingTreeModelPtr <- function(str) {
    .Call('_mlpack_DeserializeHoeffdingTreeModelPtr', PACKAGE = 'mlpack', str)
}

image_converter_call <- function(params, timers) {
    invisible(.Call('_mlpack_image_converter_call', PACKAGE = 'mlpack', params, timers))
}

kde_call <- function(params, timers) {
    invisible(.Call('_mlpack_kde_call', PACKAGE = 'mlpack', params, timers))
}

GetParamKDEModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamKDEModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamKDEModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamKDEModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeKDEModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeKDEModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeKDEModelPtr <- function(str) {
    .Call('_mlpack_DeserializeKDEModelPtr', PACKAGE = 'mlpack', str)
}

kernel_pca_call <- function(params, timers) {
    invisible(.Call('_mlpack_kernel_pca_call', PACKAGE = 'mlpack', params, timers))
}

kfn_call <- function(params, timers) {
    invisible(.Call('_mlpack_kfn_call', PACKAGE = 'mlpack', params, timers))
}

GetParamKFNModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamKFNModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamKFNModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamKFNModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeKFNModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeKFNModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeKFNModelPtr <- function(str) {
    .Call('_mlpack_DeserializeKFNModelPtr', PACKAGE = 'mlpack', str)
}

kmeans_call <- function(params, timers) {
    invisible(.Call('_mlpack_kmeans_call', PACKAGE = 'mlpack', params, timers))
}

knn_call <- function(params, timers) {
    invisible(.Call('_mlpack_knn_call', PACKAGE = 'mlpack', params, timers))
}

GetParamKNNModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamKNNModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamKNNModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamKNNModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeKNNModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeKNNModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeKNNModelPtr <- function(str) {
    .Call('_mlpack_DeserializeKNNModelPtr', PACKAGE = 'mlpack', str)
}

krann_call <- function(params, timers) {
    invisible(.Call('_mlpack_krann_call', PACKAGE = 'mlpack', params, timers))
}

GetParamRAModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamRAModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamRAModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamRAModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeRAModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeRAModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeRAModelPtr <- function(str) {
    .Call('_mlpack_DeserializeRAModelPtr', PACKAGE = 'mlpack', str)
}

lars_call <- function(params, timers) {
    invisible(.Call('_mlpack_lars_call', PACKAGE = 'mlpack', params, timers))
}

GetParamLARSPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamLARSPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamLARSPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamLARSPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeLARSPtr <- function(ptr) {
    .Call('_mlpack_SerializeLARSPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLARSPtr <- function(str) {
    .Call('_mlpack_DeserializeLARSPtr', PACKAGE = 'mlpack', str)
}

lars_predict_call <- function(params, timers) {
    invisible(.Call('_mlpack_lars_predict_call', PACKAGE = 'mlpack', params, timers))
}

lars_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_lars_train_call', PACKAGE = 'mlpack', params, timers))
}

linear_regression_call <- function(params, timers) {
    invisible(.Call('_mlpack_linear_regression_call', PACKAGE = 'mlpack', params, timers))
}

GetParamLinearRegressionPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamLinearRegressionPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamLinearRegressionPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamLinearRegressionPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeLinearRegressionPtr <- function(ptr) {
    .Call('_mlpack_SerializeLinearRegressionPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLinearRegressionPtr <- function(str) {
    .Call('_mlpack_DeserializeLinearRegressionPtr', PACKAGE = 'mlpack', str)
}

linear_regression_predict_call <- function(params, timers) {
    invisible(.Call('_mlpack_linear_regression_predict_call', PACKAGE = 'mlpack', params, timers))
}

linear_regression_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_linear_regression_train_call', PACKAGE = 'mlpack', params, timers))
}

linear_svm_call <- function(params, timers) {
    invisible(.Call('_mlpack_linear_svm_call', PACKAGE = 'mlpack', params, timers))
}

GetParamLinearSVMModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamLinearSVMModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamLinearSVMModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamLinearSVMModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeLinearSVMModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeLinearSVMModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLinearSVMModelPtr <- function(str) {
    .Call('_mlpack_DeserializeLinearSVMModelPtr', PACKAGE = 'mlpack', str)
}

lmnn_call <- function(params, timers) {
    invisible(.Call('_mlpack_lmnn_call', PACKAGE = 'mlpack', params, timers))
}

local_coordinate_coding_call <- function(params, timers) {
    invisible(.Call('_mlpack_local_coordinate_coding_call', PACKAGE = 'mlpack', params, timers))
}

GetParamLocalCoordinateCodingPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamLocalCoordinateCodingPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamLocalCoordinateCodingPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamLocalCoordinateCodingPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeLocalCoordinateCodingPtr <- function(ptr) {
    .Call('_mlpack_SerializeLocalCoordinateCodingPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLocalCoordinateCodingPtr <- function(str) {
    .Call('_mlpack_DeserializeLocalCoordinateCodingPtr', PACKAGE = 'mlpack', str)
}

logistic_regression_call <- function(params, timers) {
    invisible(.Call('_mlpack_logistic_regression_call', PACKAGE = 'mlpack', params, timers))
}

GetParamLogisticRegressionPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamLogisticRegressionPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamLogisticRegressionPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamLogisticRegressionPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeLogisticRegressionPtr <- function(ptr) {
    .Call('_mlpack_SerializeLogisticRegressionPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLogisticRegressionPtr <- function(str) {
    .Call('_mlpack_DeserializeLogisticRegressionPtr', PACKAGE = 'mlpack', str)
}

logistic_regression_classify_call <- function(params, timers) {
    invisible(.Call('_mlpack_logistic_regression_classify_call', PACKAGE = 'mlpack', params, timers))
}

logistic_regression_probabilities_call <- function(params, timers) {
    invisible(.Call('_mlpack_logistic_regression_probabilities_call', PACKAGE = 'mlpack', params, timers))
}

logistic_regression_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_logistic_regression_train_call', PACKAGE = 'mlpack', params, timers))
}

lsh_call <- function(params, timers) {
    invisible(.Call('_mlpack_lsh_call', PACKAGE = 'mlpack', params, timers))
}

GetParamLSHSearchPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamLSHSearchPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamLSHSearchPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamLSHSearchPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeLSHSearchPtr <- function(ptr) {
    .Call('_mlpack_SerializeLSHSearchPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLSHSearchPtr <- function(str) {
    .Call('_mlpack_DeserializeLSHSearchPtr', PACKAGE = 'mlpack', str)
}

mean_shift_call <- function(params, timers) {
    invisible(.Call('_mlpack_mean_shift_call', PACKAGE = 'mlpack', params, timers))
}

nbc_call <- function(params, timers) {
    invisible(.Call('_mlpack_nbc_call', PACKAGE = 'mlpack', params, timers))
}

GetParamNBCModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamNBCModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamNBCModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamNBCModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeNBCModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeNBCModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeNBCModelPtr <- function(str) {
    .Call('_mlpack_DeserializeNBCModelPtr', PACKAGE = 'mlpack', str)
}

nca_call <- function(params, timers) {
    invisible(.Call('_mlpack_nca_call', PACKAGE = 'mlpack', params, timers))
}

nmf_call <- function(params, timers) {
    invisible(.Call('_mlpack_nmf_call', PACKAGE = 'mlpack', params, timers))
}

pca_call <- function(params, timers) {
    invisible(.Call('_mlpack_pca_call', PACKAGE = 'mlpack', params, timers))
}

perceptron_call <- function(params, timers) {
    invisible(.Call('_mlpack_perceptron_call', PACKAGE = 'mlpack', params, timers))
}

GetParamPerceptronModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamPerceptronModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamPerceptronModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamPerceptronModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializePerceptronModelPtr <- function(ptr) {
    .Call('_mlpack_SerializePerceptronModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializePerceptronModelPtr <- function(str) {
    .Call('_mlpack_DeserializePerceptronModelPtr', PACKAGE = 'mlpack', str)
}

preprocess_binarize_call <- function(params, timers) {
    invisible(.Call('_mlpack_preprocess_binarize_call', PACKAGE = 'mlpack', params, timers))
}

preprocess_describe_call <- function(params, timers) {
    invisible(.Call('_mlpack_preprocess_describe_call', PACKAGE = 'mlpack', params, timers))
}

preprocess_one_hot_encoding_call <- function(params, timers) {
    invisible(.Call('_mlpack_preprocess_one_hot_encoding_call', PACKAGE = 'mlpack', params, timers))
}

preprocess_scale_call <- function(params, timers) {
    invisible(.Call('_mlpack_preprocess_scale_call', PACKAGE = 'mlpack', params, timers))
}

GetParamScalingModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamScalingModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamScalingModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamScalingModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeScalingModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeScalingModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeScalingModelPtr <- function(str) {
    .Call('_mlpack_DeserializeScalingModelPtr', PACKAGE = 'mlpack', str)
}

preprocess_split_call <- function(params, timers) {
    invisible(.Call('_mlpack_preprocess_split_call', PACKAGE = 'mlpack', params, timers))
}

CreateParams <- function(bindingName) {
    .Call('_mlpack_CreateParams', PACKAGE = 'mlpack', bindingName)
}

CreateTimers <- function() {
    .Call('_mlpack_CreateTimers', PACKAGE = 'mlpack')
}

SetParamInt <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamInt', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamDouble <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamDouble', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamString <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamString', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamBool <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamBool', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamVecString <- function(params, paramName, str) {
    invisible(.Call('_mlpack_SetParamVecString', PACKAGE = 'mlpack', params, paramName, str))
}

SetParamVecInt <- function(params, paramName, ints) {
    invisible(.Call('_mlpack_SetParamVecInt', PACKAGE = 'mlpack', params, paramName, ints))
}

SetParamMat <- function(params, paramName, paramValue, transpose) {
    invisible(.Call('_mlpack_SetParamMat', PACKAGE = 'mlpack', params, paramName, paramValue, transpose))
}

SetParamUMat <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamUMat', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamRow <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamRow', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamURow <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamURow', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamCol <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamCol', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamUCol <- function(params, paramName, paramValue) {
    invisible(.Call('_mlpack_SetParamUCol', PACKAGE = 'mlpack', params, paramName, paramValue))
}

SetParamMatWithInfo <- function(params, paramName, dimensions, paramValue) {
    invisible(.Call('_mlpack_SetParamMatWithInfo', PACKAGE = 'mlpack', params, paramName, dimensions, paramValue))
}

GetParamInt <- function(params, paramName) {
    .Call('_mlpack_GetParamInt', PACKAGE = 'mlpack', params, paramName)
}

GetParamDouble <- function(params, paramName) {
    .Call('_mlpack_GetParamDouble', PACKAGE = 'mlpack', params, paramName)
}

GetParamString <- function(params, paramName) {
    .Call('_mlpack_GetParamString', PACKAGE = 'mlpack', params, paramName)
}

GetParamBool <- function(params, paramName) {
    .Call('_mlpack_GetParamBool', PACKAGE = 'mlpack', params, paramName)
}

GetParamVecString <- function(params, paramName) {
    .Call('_mlpack_GetParamVecString', PACKAGE = 'mlpack', params, paramName)
}

GetParamVecInt <- function(params, paramName) {
    .Call('_mlpack_GetParamVecInt', PACKAGE = 'mlpack', params, paramName)
}

GetParamMat <- function(params, paramName) {
    .Call('_mlpack_GetParamMat', PACKAGE = 'mlpack', params, paramName)
}

GetParamUMat <- function(params, paramName) {
    .Call('_mlpack_GetParamUMat', PACKAGE = 'mlpack', params, paramName)
}

GetParamRow <- function(params, paramName) {
    .Call('_mlpack_GetParamRow', PACKAGE = 'mlpack', params, paramName)
}

GetParamURow <- function(params, paramName) {
    .Call('_mlpack_GetParamURow', PACKAGE = 'mlpack', params, paramName)
}

GetParamCol <- function(params, paramName) {
    .Call('_mlpack_GetParamCol', PACKAGE = 'mlpack', params, paramName)
}

GetParamUCol <- function(params, paramName) {
    .Call('_mlpack_GetParamUCol', PACKAGE = 'mlpack', params, paramName)
}

IO_GetParamMatWithInfo <- function(params, paramName) {
    .Call('_mlpack_IO_GetParamMatWithInfo', PACKAGE = 'mlpack', params, paramName)
}

ResetTimers <- function() {
    invisible(.Call('_mlpack_ResetTimers', PACKAGE = 'mlpack'))
}

SetPassed <- function(params, paramName) {
    invisible(.Call('_mlpack_SetPassed', PACKAGE = 'mlpack', params, paramName))
}

radical_call <- function(params, timers) {
    invisible(.Call('_mlpack_radical_call', PACKAGE = 'mlpack', params, timers))
}

random_forest_call <- function(params, timers) {
    invisible(.Call('_mlpack_random_forest_call', PACKAGE = 'mlpack', params, timers))
}

GetParamRandomForestModelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamRandomForestModelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamRandomForestModelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamRandomForestModelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeRandomForestModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeRandomForestModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeRandomForestModelPtr <- function(str) {
    .Call('_mlpack_DeserializeRandomForestModelPtr', PACKAGE = 'mlpack', str)
}

random_forest_classify_call <- function(params, timers) {
    invisible(.Call('_mlpack_random_forest_classify_call', PACKAGE = 'mlpack', params, timers))
}

random_forest_probabilities_call <- function(params, timers) {
    invisible(.Call('_mlpack_random_forest_probabilities_call', PACKAGE = 'mlpack', params, timers))
}

random_forest_train_call <- function(params, timers) {
    invisible(.Call('_mlpack_random_forest_train_call', PACKAGE = 'mlpack', params, timers))
}

softmax_regression_call <- function(params, timers) {
    invisible(.Call('_mlpack_softmax_regression_call', PACKAGE = 'mlpack', params, timers))
}

GetParamSoftmaxRegressionPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamSoftmaxRegressionPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamSoftmaxRegressionPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamSoftmaxRegressionPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeSoftmaxRegressionPtr <- function(ptr) {
    .Call('_mlpack_SerializeSoftmaxRegressionPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeSoftmaxRegressionPtr <- function(str) {
    .Call('_mlpack_DeserializeSoftmaxRegressionPtr', PACKAGE = 'mlpack', str)
}

sparse_coding_call <- function(params, timers) {
    invisible(.Call('_mlpack_sparse_coding_call', PACKAGE = 'mlpack', params, timers))
}

GetParamSparseCodingPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamSparseCodingPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamSparseCodingPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamSparseCodingPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeSparseCodingPtr <- function(ptr) {
    .Call('_mlpack_SerializeSparseCodingPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeSparseCodingPtr <- function(str) {
    .Call('_mlpack_DeserializeSparseCodingPtr', PACKAGE = 'mlpack', str)
}

test_r_binding_call <- function(params, timers) {
    invisible(.Call('_mlpack_test_r_binding_call', PACKAGE = 'mlpack', params, timers))
}

GetParamGaussianKernelPtr <- function(params, paramName, inputModels) {
    .Call('_mlpack_GetParamGaussianKernelPtr', PACKAGE = 'mlpack', params, paramName, inputModels)
}

SetParamGaussianKernelPtr <- function(params, paramName, ptr) {
    invisible(.Call('_mlpack_SetParamGaussianKernelPtr', PACKAGE = 'mlpack', params, paramName, ptr))
}

SerializeGaussianKernelPtr <- function(ptr) {
    .Call('_mlpack_SerializeGaussianKernelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeGaussianKernelPtr <- function(str) {
    .Call('_mlpack_DeserializeGaussianKernelPtr', PACKAGE = 'mlpack', str)
}

